// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzlxEQQzcC5fAGKIzlXE9tgzsy2roz5Xs',
    appId: '1:933926952783:web:1e2360e8855fd2c493ef3a',
    messagingSenderId: '933926952783',
    projectId: 'stockgram-70916',
    authDomain: 'stockgram-70916.firebaseapp.com',
    storageBucket: 'stockgram-70916.appspot.com',
    measurementId: 'G-6FCBFXZXB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV_Btr98Gqy1nuZnayYKaMYUmCxRZcroM',
    appId: '1:933926952783:android:7c8b62caeefc73dd93ef3a',
    messagingSenderId: '933926952783',
    projectId: 'stockgram-70916',
    storageBucket: 'stockgram-70916.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKKLwg0efhU-GhZUrBWrib3mn0mb9uxyM',
    appId: '1:933926952783:ios:029318e5ad2e140693ef3a',
    messagingSenderId: '933926952783',
    projectId: 'stockgram-70916',
    storageBucket: 'stockgram-70916.appspot.com',
    iosBundleId: 'com.jai.stockgram.stockgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKKLwg0efhU-GhZUrBWrib3mn0mb9uxyM',
    appId: '1:933926952783:ios:029318e5ad2e140693ef3a',
    messagingSenderId: '933926952783',
    projectId: 'stockgram-70916',
    storageBucket: 'stockgram-70916.appspot.com',
    iosBundleId: 'com.jai.stockgram.stockgram',
  );
}
